package onodes.RMI.ServerGeneric;

import java.rmi.RemoteException;

import onodes.RMI.ControllerRMI;

/**
 *
 * DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
 *
 * Ce module defini les elements de bases indispensable afin de developper un module
 * utilisant RMI en tant que serveur.
 * 
 * Le fonctionnement est tel que le developpeur doit redefinir un module RMI Serveur
 * pour son application. Et il y insere les methodes qu'il souhaite voir etre utilisable
 * 
 * Tout element d'un module souhaitant interagir avec du RMI en ecrivant ses 
 * methodes devra donc etendre les elements relatif de ce module.
 * 
 * @author groupe1
 *
 */
public abstract class ControllerRMIServerGeneric<M extends ModelRMIServerGeneric, V extends ViewRMIServerGeneric>
		extends ControllerRMI<ModelRMIServerGeneric, ViewRMIServerGeneric> {

	/**
	 * @throws RemoteException
	 */
	public ControllerRMIServerGeneric() throws RemoteException {
		super();
	}
	
	/**
	 * @param model
	 * @param view
	 * @throws RemoteException
	 */
	public ControllerRMIServerGeneric(M model, V view) throws RemoteException {
		super(model, view);
	}
}
