package onodes.RMI.ServerGeneric;

import java.rmi.RemoteException;

import onodes.RMI.ControllerRMI;

/**
 *
 * DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
 * 
 * @author groupe1
 *
 */
public abstract class ControllerRMIServerGeneric<M extends ModelRMIServerGeneric, V extends ViewRMIServerGeneric>
		extends ControllerRMI<ModelRMIServerGeneric, ViewRMIServerGeneric> {

	/**
	 * @throws RemoteException
	 */
	public ControllerRMIServerGeneric() throws RemoteException {
		super();
	}
	
	/**
	 * @param model
	 * @param view
	 * @throws RemoteException
	 */
	public ControllerRMIServerGeneric(M model, V view) throws RemoteException {
		super(model, view);
	}
}
