package onodes.RMI.ServerGeneric;

import java.rmi.Remote;
import java.rmi.RemoteException;

import onodes.RMI.ClientGeneric.ModelRMIClientGenericRemote;

/*
 * Besoin de conserver la même architecture de package dans Le serveur comme le client
 * afin que les classes puissent être trouvé lors du Naming.lookup()
 */

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
 * @param <MC>
*
*/
public interface ModelRMIServerGenericRemote<MC extends ModelRMIClientGenericRemote> extends Remote {
	/**
	 * 
	 * @return
	 * @throws RemoteException
	 */
	public String getInfoServer() throws RemoteException;

	/**
	 * 
	 * @param client
	 * @throws RemoteException
	 */
	void registerClient(MC client) throws RemoteException;
}
