package onodes.RMI.Client;

import java.rmi.RemoteException;

import onodes.RMI.ControllerRMI;
import onodes.RMI.Server.ModelRMIServerRemote;
import pnodes.monAppClient.ControllerMonAppClient;

/*
 * Besoin de conserver la même architecture de package dans Le serveur comme le client
 * afin que les classes puissent être trouvé lors du Naming.lookup()
 */

/**
 *
 * DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
 * 
 * @author groupe1
 *
 */
public class ControllerRMIClient extends
		ControllerRMI<ModelRMIClient, ViewRMIClient> {

	public ControllerRMIClient(ControllerMonAppClient controllerAppClient) throws RemoteException {
		super();
		model=new ModelRMIClient(controllerAppClient);
	}
	
	public Object invokeMethodOnControllerAppServer(String methodName, Class[] cArgs, Object[] oArgs) {
		return model.invokeMethodOnControllerAppServer(methodName, cArgs, oArgs);
	}
}
