package onodes.RMI.Client;

import java.rmi.RemoteException;

import onodes.Controller;
import onodes.RMI.ControllerRMI;

/*
 * Besoin de conserver la même architecture de package dans Le serveur comme le client
 * afin que les classes puissent être trouvé lors du Naming.lookup()
 */

/**
 *
 * DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
 * 
 * 
 * Ce module defini les elements necessaire pour pouvoir appeler une methode
 * sur une autre application en tant que client.
 * 
 * Le fonctionnement est tel que le developpeur n'a pas a redefinir un module RMI Client
 * pour son application.
 * Il suffit que dans ses modeles il instancie ce controlleur pour pouvoir appeller des methodes
 * sur une application serveur.
 * 
 * Cela se fait par le biais de invokeMethodOnAllControllerAppClient() le devellopeur 
 * appele cette methode en indiquant les caracteristiques de la methode qu'il souhaite
 * appeler sur le controleur de l'application serveur.
 * 
 * Ici les deux modules RMIServer et RMIClient servent "d'intermediaire" il ne font que
 * relayer la methode et le modele RMIServer instancie indirectement par l'application Serveur
 * tentera d'invoquer la methode sur le controlleur de l'application serveur. Dans le cas ou
 * elle existe sur ce dernier. 
 * 
 * Pour une utilisation simple il n'y a donc pas besoin de creer un module qui etend ce dernier.
 * 
 * @author groupe1
 *
 */
public class ControllerRMIClient<C extends Controller> extends
		ControllerRMI<ModelRMIClient, ViewRMIClient> {

	/**
	 * @param controllerAppClient
	 * @throws RemoteException
	 */
	public ControllerRMIClient(C controllerAppClient) throws RemoteException {
		super();
		model=new ModelRMIClient(controllerAppClient);
	}
	
	/**
	 * @param controllerAppClient
	 * @param ip
	 * @throws RemoteException
	 */
	public ControllerRMIClient(C controllerAppClient, String ip) throws RemoteException {
		super();
		model=new ModelRMIClient(controllerAppClient, ip);
	}
	
	/**
	 * @param methodName
	 * @param cArgs
	 * @param oArgs
	 * @return
	 */
	public Object invokeMethodOnControllerAppServer(String methodName, Class[] cArgs, Object[] oArgs) {
		return model.invokeMethodOnControllerAppServer(methodName, cArgs, oArgs);
	}
}
