package onodes;


/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
*
*/
public abstract class Controller<M extends Model, V extends View> {
	protected M model;
	protected V view;
}
