package onodes;

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* 
* Classe Abstraite définissant les élements de base d'un controleur.
* Chaque controleur d'un "module" / "package" défini selon le pattern MVC simplifié
* devra étendre cette Class ou une Classe fille.  
* 
* @author groupe1
*
*/
public abstract class Controller<M extends Model, V extends View> {
	/**
	 * 
	 */
	protected M model;
	/**
	 * 
	 */
	protected V view;
	
	/**
	 * 
	 */
	public Controller() {
		this.model=null;
		this.view=null;
	}
	
	/**
	 * @param model
	 * @param view
	 */
	public Controller(M model, V view) {
		this.model=model;
		this.view=view;
	}
}
