package onodes;


/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
*
*/
public abstract class Controller<M extends Model, V extends View> {
	protected M model;
	protected V view;
	
	public Controller() {
		this.model=null;
		this.view=null;
	}
	
	public Controller(M model, V view) {
		this.model=model;
		this.view=view;
	}
}
