package onodes;

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* 
* Interface définissant les élements de base d'un modele.
* Chaque modele d'un "module" / "package" défini selon le pattern MVC simplifié
* devra etendre cette Class ou une Classe fille.
* 
* @author groupe1
*
*/
public interface Model {

}
