package onodes;

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* 
* Interface définissant les élements de base d'une vue.
* Chaque vue d'un "module" / "package" défini selon le pattern MVC simplifié
* devra etendre cette Class ou une Classe fille.
* 
* @author groupe1
*
*/
public interface View {

}
