package onodes.RMI;

import java.rmi.Remote;

import onodes.View;

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
*
*/
public abstract class ViewRMI implements View, Remote {

}
