package pnodes.monappli.rmiserver;

import java.rmi.RemoteException;

import onodes.RMI.Server.ControllerRMIServer;

/**
 *
 * DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
 * 
 * @author groupe1
 *
 */
public class ControllerMonAppRMIServer extends
		ControllerRMIServer<ModelMonAppRMIServer, ViewMonAppRMIServer> {

	public ControllerMonAppRMIServer() throws RemoteException {
		this.model = new ModelMonAppRMIServer();
		this.view = new ViewMonAppRMIServer();
	}

	public ControllerMonAppRMIServer(ModelMonAppRMIServer model,
			ViewMonAppRMIServer view) throws RemoteException {
		super(model, view);
	}

}
