package controller;

import java.rmi.RemoteException;

import view.VRMIServer;
import model.MRMIServer;

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
*
*/
public class CRMIServer extends CRMI<MRMIServer, VRMIServer> {
	public CRMIServer() throws RemoteException {
		super();
		this.model = new MRMIServer();
		//this.view = new VRMIServer();
	}
}
