package core.pcore;

import java.rmi.RemoteException;

import controller.CRMIClient;

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
*
*/
public final class CoreApp {
	/**
	 * Main code of the application
	 * DevOps Write some code here
	 * @param args
	 */
	public static void mainApp(String[] args) {
		//TEST RMI CLIENT
		try {
			CRMIClient test = new CRMIClient("127.0.0.1");
		} catch (RemoteException e) {
			e.printStackTrace();
		}
		
	}

	/*
	 * Main functions of the application
	 * DevOps Write some functions here
	 */
	
}
