package core.pcore;

import java.rmi.RemoteException;

import onodes.RMI.Client.ControllerRMIClient;
import onodes.RMI.Server.ControllerRMIServer;

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
*
*/
public final class CoreApp {
	/**
	 * Main code of the application
	 * DevOps Write some code here
	 * @param args
	 */
	public static void mainApp(String[] args) {
		//TEST RMI CLIENT
		try {
			ControllerRMIServer machin = new ControllerRMIServer();
			
			Thread.sleep(100);
			
			ControllerRMIClient test = new ControllerRMIClient(); //"127.0.0.1"
			
			//Thread.sleep(1000);
		} catch (RemoteException e) {
			e.printStackTrace();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}

	/*
	 * Main functions of the application
	 * DevOps Write some functions here
	 */
	
}
