package onodes.RMI.Server;

import java.rmi.RemoteException;

import onodes.RMI.ControllerRMI;

/**
 *
 * DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
 * 
 * @author groupe1
 *
 */
public class ControllerRMIServer extends
		ControllerRMI<ModelRMIServer, ViewRMIServer> {
	public ControllerRMIServer() throws RemoteException {
		super();
		this.model = new ModelRMIServer();
		// this.view = new VRMIServer();
	}
}
