package onodes.RMI.Server;

import java.rmi.Remote;
import java.rmi.RemoteException;

import onodes.RMI.Client.ModelRMIClientRemote;

/*
 * Besoin de conserver la même architecture de package dans Le serveur comme le client
 * afin que les classes puissent être trouvé lors du Naming.lookup()
 */

/**
*
* DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
* @author groupe1
*
*/
public interface ModelRMIServerRemote extends Remote {
	/**
	 * 
	 * @return
	 * @throws RemoteException
	 */
	public String getInfoServer() throws RemoteException;

	/**
	 * 
	 * @param client
	 * @throws RemoteException
	 */
	void registerClient(ModelRMIClientRemote client) throws RemoteException;
}
