package core;

import model.Model;
import core.pcore.CoreApp;

/**
*
* DO NOT EDIT THIS FILE
* @author groupe1
*
*/
public class Core {

	public static void main(String[] args) {
		System.out.println("Lancement Main Core");
		/*
		 * Parse of configs files
		 */
		
		/*
		 * Activation of listed models
		 */
		try {
			
			/*
			 * A MODIFIER PARSER FICHIER + LANCEMENT AUTOMATIQUE
			 */
			Class<?> exemple = Class.forName("model.ModelRMIServer");
			Model modele = (Model) exemple.newInstance();
			
			try {
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			Class<?> exemple2 = Class.forName("model.ModelRMIClient");
			Model modele2 = (Model) exemple2.newInstance();
			Model modele3 = (Model) exemple2.newInstance();
			
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		/*
		 * Execution of the mainApp() written by devOps
		 */
		//CoreApp application = new CoreApp();
		//application.mainApp(args);
		CoreApp.mainApp(args);
	}

}
