package pnodes.monAppServerGeneric.rmiserver;

import java.rmi.RemoteException;
import onodes.RMI.ServerGeneric.ControllerRMIServerGeneric;

/**
 *
 * DO NOT EDIT THIS FILE IT BELONG TO THE FRAMEWORK
 * 
 * @author groupe1
 *
 */
public class ControllerMonAppRMIServer extends
		ControllerRMIServerGeneric<ModelMonAppRMIServer, ViewMonAppRMIServer> {

	/**
	 * @throws RemoteException
	 */
	public ControllerMonAppRMIServer() throws RemoteException {
		this.model = new ModelMonAppRMIServer();
		this.view = new ViewMonAppRMIServer();
	}

	/**
	 * @param model
	 * @param view
	 * @throws RemoteException
	 */
	public ControllerMonAppRMIServer(ModelMonAppRMIServer model,
			ViewMonAppRMIServer view) throws RemoteException {
		super(model, view);
	}
}
